# Generated by Django 3.2.4 on 2021-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('published_date', models.IntegerField(default=0)),
                ('average_rating', models.IntegerField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=10000)),
                ('categories', models.ManyToManyField(to='books_api.Category')),
            ],
        ),
    ]
