# Generated by Django 3.2.4 on 2021-06-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0003_auto_20210618_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
