# Generated by Django 3.2.4 on 2021-06-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0005_auto_20210621_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='category',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='books_api.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='books_api.Category'),
        ),
    ]
