# Generated by Django 3.2.4 on 2021-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0007_rename_category_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
